[target.thumbv6m-none-eabi]
#runner = 'arm-none-eabi-gdb'
runner = "gdb"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv6m-none-eabi"

[profile.dev.package."*"]
opt-level = "s"
