[toolchain]
components = [ "rust-analyzer", "rust-src", "llvm-tools" ]
targets = [ "thumbv6m-none-eabi" ]
profile = "default"

#channel = "1.80.0"
# -> We need features from the nightly version.
# -> `rustc --version`
# -> Well, there isn't really any equivalent version.
# see https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
# and https://doc.rust-lang.org/cargo/reference/unstable.html#build-std-features
#channel = "nightly-2024-06-22"
channel = "nightly-2024-08-22"

# We had to do this for some older nightlies but the current one seems to be ok:
# dir=/home/user/.rustup/toolchains/nightly-2024-06-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu
# patchelf --add-rpath /nix/store/v2ny69wp81ch6k4bxmp4lnhh77r0n4h1-zlib-1.3.1/lib $dir/bin/rust-lld
# patchelf --add-rpath /nix/store/v2ny69wp81ch6k4bxmp4lnhh77r0n4h1-zlib-1.3.1/lib $dir/bin/gcc-ld/ld.lld
# patchelf --set-interpreter /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/ld-linux-x86-64.so.2 $dir/bin/gcc-ld/*
